# emj_setenv.R
# Set environment variables for general use

e <- new.env()

## Constants of use in NTK analysis
## LLMR and ULMR as per Roche documentation
## Cutoffs for AD biomarkers generated by TJB via ROC analysis
## Others generated by +2sigma method by EMJ, CVH

LLMR        <- c(0,200,8,80,0,0,0,0,1.5)
names(LLMR) <- c("ABeta_1_40","ABeta_1_42","pTau","tTau","Inv_ABeta_1_42_derived","ABeta_1_42_40_derived","pTau_ABeta_1_42_derived","tTau_ABeta_1_42_derived","IL6")
ULMR        <- c(Inf,1700,120,1300,Inf,Inf,Inf,Inf,Inf)
names(ULMR) <- c("ABeta_1_40","ABeta_1_42","pTau","tTau","Inv_ABeta_1_42_derived","ABeta_1_42_40_derived","pTau_ABeta_1_42_derived","tTau_ABeta_1_42_derived","IL6")
cutoff        <- c(0.046, 0.038, 513.9, 24.8, 293, 266, 1296, 209)
names(cutoff) <- c("ABeta_1_42_40_derived","pTau_ABeta_1_42_derived", "ABeta_1_42", "pTau", "tTau", "a_Synuclein", "Neurogranin", "NFL")

hellno      <- FALSE

tab_model.css <- list(css.thead='padding:0.0cm;', css.tdata='padding:0.1cm;', css.summary='padding-top:0.0cm; padding-bottom:0.0cm;')

save(list=ls(envir=e), envir=e, file="R/sysdata.rda")
